### PR TITLE
Target port number

### PR DESCRIPTION
**Pull request by koudaiii**
## WHY

nginx-basic-auth-proxy is only 80 port.
I want to specify a port number.

## WHAT

I made it possible to specify the port number in nginx-basic-auth-proxy.

### CODE REVIEW

**Comment by dtan4** [comment]
Please append this option to README (Enviroment variables -> Optional) 🙏

**Comment by dtan4** [comment]
Other optional variables are set default values at `Dockerfile`.
https://github.com/dtan4/nginx-basic-auth-proxy/blob/e42a907e35692b463e9562a57b0ab0301b82aa10/Dockerfile

Please follow this manner.

**Comment by koudaiii** [comment]
> Other optional variables are set default values at Dockerfile.

Ok. I will fix.

**Comment by koudaiii** [comment]
> Please append this option to README (Enviroment variables -> Optional) 🙏

Fix !!

**Comment by dtan4** [comment]
LGTM 👍

**Pull request merged**
